main: de.rangun.pinkbull.PinkBullPlugin
name: PinkBull
version: '@version@'
description: PinkBull verleiht Flügel!
author: Velnias75
website: https://www.spigotmc.org/resources/pinkbull.102050/
commands:
  fly:
    description: enables the player to just fly unlimited.
    permission: pinkbull.fly
    usage: /fly [<player>]
  pinkbull:
    description: gives the player a free PinkBull with optional duration in seconds.
    permission: pinkbull.pinkbull
    usage: /pinkbull [<duration>]
api-version: '1.17'
