main: de.rangun.pinkbull.PinkBullPlugin
name: PinkBull
version: '@version@'
description: PinkBull verleiht Flügel!
author: Velnias75
website: https://www.spigotmc.org/resources/pinkbull.102050/
commands:
  fly:
    description: Setzt oder nimmt Spieler in den bzw. aus dem Flugmodus
    permission: pinkbull.fly
    usage: /fly [player]
  pinkbull:
    description: Gibt dem Spieler einen PinkBull-Trank
    permission: pinkbull.pinkbull
    usage: /pinkbull
api-version: '1.17'
